# This is a basic workflow that is manually triggered

name: Manual workflow

env:
 manager: king
 founder: queen
 owner: Domnic Raj D
uses: actions/cache@v2
with:
 path: .path/
 key: ${{ runner.os }}-venv-${{ hashFiles('.venv/') }} 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch, push]    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
     owner: Dom
     co-owner: Raj
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: cache
      uses: actions/cache@v2
      with:
       path: .en/
       key: ${CI_COMMIT_REF_SLUG}
       
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
      
    - name: Run a one-line script
      run: echo Hello, world!!
      
  test:
  - name: steps
    run: echo Hello
  
