# This is a basic workflow that is manually triggered

name: Manual workflow

env:
 manager: king
 founder: queen
 owner: Domnic Raj D

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: 
  push:
    branches: [ master ]      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
     owner: Dom
     co-owner: Raj
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: cache
      uses: actions/cache@v2
      with:
       path: .en/
       key: ${CI_COMMIT_REF_SLUG}
       
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
      
    - name: Run a one-line script
      run: echo Hello, world!

  test:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run a multi-line script
      run: |
       echo Add other actions to build,
       echo test, and deploy your project
       echo " who: $manager"
       echo " auth: $owner"
          
    - name: Env set 
      env: # Or as an environment variable
       user: ${{ secrets.domenv }}
       stage: dev
      run: echo $user $stage > /home/ddomnicraj/actions-runner/file.txt

  test1:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run a multi-line script
      run: echo " Test "
      
  validation:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [test1,deploy]
    steps:
    - name: Run a multi-line script
      run: echo " Test "
      

  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: test
    steps:
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: |
        ./pom.html
        /home/ddomnicraj/actions-runner/file.txt
       retention-days: 1

    - name: Artifacts1
      uses: actions/upload-artifact@v2
      with:
       name: Domnic_file
       path: /home/ddomnicraj/actions-runner/en
       retention-days: 1
   
  sync:
   runs-on: self-hosted
   needs: deploy
   steps:
   - name: composite action
     uses: ddomnicraj/maven@dev-domnicraj
