# This is a basic workflow that is manually triggered

name: Manual workflow

env:
 manager: king
 founder: queen
 owner: Domnic Raj D

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - dev-domnicraj
    tags:        
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: ${{ github.ref == 'refs/tags/v2' }}
    runs-on: self-hosted
    env:
     owner: Dom
     co-owner: Raj
    steps:
    - name: test flow
      uses: ddomnicraj/maven@master
