# This is a basic workflow that is manually triggered

name: Manual workflow

env:
 manager: king
 founder: queen
 owner: Domnic Raj D

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: 
  push:
    branches: [ dev-patch ]      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: self-hosted
    env:
     owner: Dom
     co-owner: Raj
    steps:
    - name: test flow
      uses: ddomnicraj/maven@master
